# Copyright 2026 Dotanuki Labs
# SPDX-License-Identifier: AGPL-3.0-or-later

blank_issues_enabled: false
contact_links:
  - name: Discussions Forum
    url: https://github.com/dotanuki-labs/grapsus/discussions
    about: Use this space to ask and answer questions and follow community annoucements.
