# Copyright 2026 Dotanuki Labs
# SPDX-License-Identifier: AGPL-3.0-or-later

name: ci-compliance

permissions:
  contents: read

on:
  workflow_call:

jobs:
  checks:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 20
          persist-credentials: false

      - name: Check typos on source files
        uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d # v1.44.0

      - name: Check commit conventions
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: crate-ci/committed@faeed42f2e10c244533a01525f13c4d8b6ce383f # v1.1.11

      - name: Check MIT license on source files
        run: docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye:v6.3.0 check

      - name: Check issues with GHA Workflows
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          advanced-security: false
